version: '3.1'

services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=bechdel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bechdel
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
      - frontend

volumes:
  dbdata:
    external:
      name: bechdel_dbdata