# Generated by Django 3.2.13 on 2022-06-08 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMetaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('releaseDate', models.DateField(db_index=True)),
                ('genre', models.IntegerField(choices=[(0, 'Action'), (1, 'Horror'), (2, 'Comedy'), (3, 'Adventure'), (4, 'Drama'), (5, 'Thriller/Suspense'), (6, 'Musical'), (7, 'Romantic Comedy'), (8, 'Western'), (9, 'Black Comedy')], db_index=True)),
                ('gross', models.PositiveBigIntegerField(db_index=True)),
                ('image', models.ImageField(default='posters/default.jpg', upload_to='posters/')),
                ('bechdelResult', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResultsModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('movieId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.moviemetamodel')),
                ('bRule1Result', models.BooleanField(blank=True, help_text='Has at least two named women', null=True)),
                ('bRule2Result', models.BooleanField(blank=True, help_text='Who speak to each other', null=True)),
                ('bRule3Result', models.BooleanField(blank=True, help_text='About something other than a man', null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
