# Generated by Django 3.2.13 on 2022-07-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviemetamodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemetamodel',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (1, 'Horror'), (2, 'Comedy'), (3, 'Adventure'), (4, 'Drama'), (5, 'Thriller'), (6, 'Musical'), (7, 'Romcom'), (8, 'Western'), (9, 'Bcomedy'), (10, 'Other')], db_index=True),
        ),
        migrations.AlterField(
            model_name='moviemetamodel',
            name='image',
            field=models.ImageField(default='assets/default.jpg', upload_to='assets/posters/'),
        ),
    ]
