# Generated by Django 3.2.13 on 2022-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220717_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemetamodel',
            name='image',
            field=models.ImageField(default='assets/default.jpg', upload_to='posters/'),
        ),
    ]
